wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1707901068.129925
    t:
      1:
      - 1
      - 11
      - 12
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 12
      - 49
      - 51
      - 55
      3:
      - 23
      4: 3.12.1
      5: 0.16.3
      6: 4.37.2
      8:
      - 2
      - 5
      13: linux-x86_64
