wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/train.py
    python_version: 3.9.6
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1710991471.0
    t:
      1:
      - 1
      - 11
      - 12
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 12
      - 49
      - 51
      - 55
      3:
      - 23
      4: 3.9.6
      5: 0.16.4
      6: 4.37.2
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
